[package]
name = "midas-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.51"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"
structopt = "0.3.25"
