[package]
name = "frob-brightness"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Tool to control backlight brightness"
repository = "https://github.com/panicbit/frob"
readme = "../README.md"

[dependencies]
dbus = "0.9.5"
fauxpas = "1.0.51"
structopt = "0.3.25"
