[package]
name = "midas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midas-monitor = { version = "0.1.0", path = "../midas-monitor" }

anyhow = "1.0.51"
structopt = "0.3.25"
